### ISSUE TITLE
name collusion with xlang-ai/OpenAgents

### ISSUE THREAD

**Issue by chymian** [OpenAgentsInc/openagents#42]
tracing  GPUtopia for a while, I saw your announcement yesteraday and wondered, why a already occupied name was choosen?

https://github.com/xlang-ai/OpenAgents

**Comment by AtlantisPleb** [comment]
Thank you for the note. The collision was not intentional and this is the first I've heard of that project. 

Hopefully there can be collaboration between our projects in the future. For example I'd love to see their agents connected to our micropayments layer, such that every contributor to that project could be paid through ours.
